/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
export type User = {
  /**
   * @format uuid
   */
  id?: string;
  username?: string;
  password?: string;
  role?: "SUPERADMIN" | "ADMIN" | "USER";
};

export type AuthRequest = {
  username?: string;
  password?: string;
};
